[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#   Inject brainstorm key handler
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = "if key == 'enter' then key = 'return' end"
position = "after"
payload = '''
local brainstorm = require("brainstorm")
brainstorm.keyHandler(self, key, dt)
'''
match_indent = true
overwrite = false

#   Inject autoreroll update loop
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.FRAMES.MOVE = G.FRAMES.MOVE + 1"
position = "before"
payload = '''
local brainstorm = require("brainstorm")
brainstorm.update(dt)
'''
match_indent = true
overwrite = false

#   Inject autoreroll update loop
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "return function()"
position = "before"
payload = '''
local brainstorm = require("brainstorm")
brainstorm.loadConfig()
'''
match_indent = true
overwrite = false

#   Add core.lua to module list
[[patches]]
[patches.module]
source = "main.lua"
before = "main.lua"
name = "brainstorm"